spring:
  application:
    name: didacto
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4001/didacto-db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
        default_batch_fetch_size: 100
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


jwt:
  secret1: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

imp:
  api:
    key: 6213286820175160
    secretkey: jFHaAVeJAK12x2K7yhdKEbxm5KKGK03Is5PdWNMuaxuwZSH9MG4abidehgwdAd3c2WzgpbrR51KYpSb7

payment:
  test-mode : true

# Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /login

# Exception handler
error:
  printStackTrace: true # Stack trace 출력 여부
  printStackTraceLine: 10 # Stack trace 출력 줄 수

rabbitmq:
  queue:
    name: monitoring-image-queue
  exchange:
    name: monitoring-image-exchange
  routing:
    key : monitoring-image-key